CREATE_COLLECTION_API = 'https://test.targeto.io/api/V0.0.1/publicApis/collection/createCollection'
UPLOAD_PROFILE_API = 'https://test.targeto.io/api/V0.0.1/publicApis/collection/uploadData'
VALIDATION_API = 'https://test.targeto.io/api/V0.0.1/publicApis/authentication/token'
CONFIG_API = 'https://test.targeto.io/api/V0.0.1/config/config-set'
GET_TRANSFORMATION_STRUCTURE_API = 'https://test.targeto.io/api/V0.0.1/dcr/12233/sdt/transformation/'
GET_SDT_DATA_API = 'https://test.targeto.io/api/V0.0.1//dcr/126/sdt/data/'
SET_SDT_DATA_API = 'https://test.targeto.io/api/V0.0.1/dcr/126/sdt/data/'